### ISSUE TITLE
Race condition: An item with the same key has already been added

### ISSUE THREAD

**Issue by Nikkelmann** [leekelleher/umbraco-contentment#218]
### Which Contentment version are you using?

3.2.0

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.5.0

### Bug summary

Sometimes when `/umbraco/backoffice/umbracoapi/content/GetEmptyByKeys` is called multiple times on the same page, it ends up in a race condition where multiple threads tries to populate the _lookout dictionary with the same key.

### Steps to reproduce

Setup a blocklist within a blocklist and add blocks of the same type.

```
ExceptionMessage:
An item with the same key has already been added. Key: MyProject.Models.Enums.ImageLayoutOptions

ExceptionType:
System.ArgumentException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

StackTrace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Umbraco.Community.Contentment.DataEditors.EnumDataListSource.PopulateLookup(Type type)
   at Umbraco.Community.Contentment.DataEditors.EnumDataListSource.GetValueType(Dictionary`2 config)
   at Umbraco.Community.Contentment.DataEditors.EnumDataListSource.GetItems(Dictionary`2 config)
   at Umbraco.Community.Contentment.DataEditors.DataListConfigurationEditor.ToValueEditor(Object configuration)
   at Umbraco.Cms.Core.Models.Mapping.ContentPropertyDisplayMapper.Map(IProperty originalProp, ContentPropertyDisplay dest, MapperContext context)
   at Umbraco.Cms.Core.Models.Mapping.ContentPropertyMapDefinition.Map(IProperty source, ContentPropertyDisplay target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.<>c__DisplayClass9_0`2.<Define>b__1(Object source, Object target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, MapperContext context)
   at Umbraco.Cms.Core.Mapping.MapperContext.Map[TSource,TTarget](TSource source)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Cms.Core.Mapping.MapperContext.MapEnumerable[TSourceElement,TTargetElement](IEnumerable`1 source)
   at Umbraco.Cms.Core.Models.Mapping.TabsAndPropertiesMapper.MapProperties(IContentBase content, List`1 properties, MapperContext context)
   at Umbraco.Cms.Core.Models.Mapping.TabsAndPropertiesMapper`1.Map(TSource source, MapperContext context)
   at Umbraco.Cms.Web.BackOffice.Mapping.ContentMapDefinition.Map(IContent source, ContentVariantDisplay target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.<>c__DisplayClass9_0`2.<Define>b__1(Object source, Object target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, MapperContext context)
   at Umbraco.Cms.Core.Mapping.MapperContext.Map[TTarget](Object source)
   at Umbraco.Cms.Core.Models.Mapping.ContentVariantMapper.CreateVariantDisplay(MapperContext context, IContent content, Language language, String segment)
   at Umbraco.Cms.Core.Models.Mapping.ContentVariantMapper.<>c__DisplayClass3_0.<Map>b__0(Language language)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Umbraco.Cms.Core.Models.Mapping.ContentVariantMapper.Map(IContent source, MapperContext context)
   at Umbraco.Cms.Web.BackOffice.Mapping.ContentMapDefinition.Map(IContent source, ContentItemDisplay target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.<>c__DisplayClass9_0`2.<Define>b__1(Object source, Object target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Action`1 f)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.MapToDisplay(IContent content, Action`1 contextOptions)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.GetEmpties(IEnumerable`1 contentTypes, Int32 parentId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.GetEmptyByKeysInternal(Guid[] contentTypeKeys, Int32 parentId)
   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.GetEmptyByKeys(ContentTypesByKeys contentTypeByKeys)
   at lambda_method943(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

**Comment by Nikkelmann** [comment]
A workaround could be changing to a ConcurrentDictionary and use [TryAdd()](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.tryadd?view=net-6.0) instead.

https://github.com/leekelleher/umbraco-contentment/blob/63192e10384387b3e2fcf4edbbce5d8a18bb317d/src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/EnumDataListSource.cs#L97

**Comment by Nikkelmann** [comment]
@leekelleher 
It happens at two blocks in my current solution, but I think it was after umbraco 9.3 it began (uncomfirmed).
I'll see if I can setup a clean solution and make it fail there.

**Comment by leekelleher** [comment]
@Nikkelmann I've tried adding several Block List editors on a page, some with nested Block List editors, but I wasn't able to reproduce the issue. This was on my local machine using Umbraco v8.17 and v9.0, _(I didn't test on latest v9.x, mostly as I'd need to make a new test suite, but also I wouldn't expect Block List to make any significant API updates in the minor releases)._

Still, I can totally see how the concurrency race condition would happen, so I've refactored the code to use a `ConcurrentDictionary`, see commit ea686a5b527161f05642064e0276af27cecf2acc.

I'll get a v3.3.1 patch release out as soon as I can. 👍

**Comment by leekelleher** [comment]
...and [Contentment v3.3.1](https://github.com/leekelleher/umbraco-contentment/releases/tag/3.3.1) has been released.
