### ISSUE TITLE
Smidge Issue in Production

### ISSUE THREAD

**Issue by TRexStark** [leekelleher/umbraco-contentment#294]
### Which Contentment version are you using?

4.4.0

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

10.3.2

### Bug summary

I published a brand new site which works in my local perfectly of course. After publishing, I started having problems with umbraco-backoffice-css returning 500 and things are broken in the backoffice. Upon a lot of trials and errors, I turned debug true in production's appSettings which made everything work in exception to Contentment and other packages.

Then I turned the debug back to false and the Log shows 1 single error:

```
System.IO.FileNotFoundException: No such file exists /App_Plugins/Contentment/contentment.css (mapped from /App_Plugins/Contentment/contentment.css)
File name: '/App_Plugins/Contentment/contentment.css'
   at Smidge.SmidgeFileSystem.GetRequiredFileInfo(IWebFile webfile)
   at Smidge.FileProcessors.PreProcessManager.<>c__DisplayClass7_0.<ProcessFileImpl>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.CreateValue()
   at Smidge.FileProcessors.PreProcessManager.ProcessFileImpl(IWebFile file, BundleOptions bundleOptions, BundleContext bundleContext)
```

Please let me know if you need the full Trace.

### Steps to reproduce

Publish a site using v10.3.2 to production.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome

**Comment by TRexStark** [comment]
Please ignore. I found the issue was with another package. sorry about this.

**Comment by leekelleher** [comment]
@TRexStark No worries, thanks for following up on it. 👍
