### ISSUE TITLE
Umbraco 13, ToArtifact method signature mismatch

### ISSUE THREAD

**Issue by slag-dev** [leekelleher/umbraco-contentment#383]
### Which Contentment version are you using?

4.6.0

### Which Umbraco version are you using? For example: 10.3.2 - don't just write v10

13.1.1

### Bug summary

When attempting to deploy new update on Umbraco Cloud we get following errors:

### Steps to reproduce

Unhandled exception. System.Reflection.ReflectionTypeLoadException: Could not load all types from "Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType[T](ITypeFinder typeFinder, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass21_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at SLAG.Web.Startup.ConfigureServices(IServiceCollection services) in C:\home\site\repository\src\SLAG.Web\Startup.cs:line 41
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass7_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
   at SLAG.Web.Program.Main(String[] args) in C:\home\site\repository\src\SLAG.Web\Program.cs:line 6
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.Unhandled exception. System.Reflection.ReflectionTypeLoadException: Could not load all types from "Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType[T](ITypeFinder typeFinder, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass21_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at SLAG.Web.Startup.ConfigureServices(IServiceCollection services) in C:\home\site\repository\src\SLAG.Web\Startup.cs:line 41
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass7_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
   at SLAG.Web.Program.Main(String[] args) in C:\home\site\repository\src\SLAG.Web\Program.cs:line 6
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

**Comment by leekelleher** [comment]
@slag-dev Thanks for reporting this.

I'm confused by this error, as this was a specific fix I had to do in order to support Umbraco v13.x. The relevant `ToArtifact` method is there. https://github.com/leekelleher/umbraco-contentment/blob/4.6.0/src/Umbraco.Community.Contentment/DataEditors/EditorNotes/EditorNotesConfigurationConnector.cs#L73-L77

I haven't used Umbraco Cloud in several years, so I'm not sure if something is particularly different with that set-up. 🤔

**Comment by leekelleher** [comment]
@slag-dev To clarify a couple of things, does this work on your local environment? and only happens when you deploy up to Umbraco Cloud?

I'm wondering if there's a .NET version mismatch on Umbraco Cloud environments. Which is causing an issue with the .NET multi-targeting code that Contentment is using. Hmmm. 🤔

**Comment by slag-dev** [comment]
@leekelleher everything works locally, but not when I deploy it on Umbraco Cloud.

That's a good question with .NET version i will clarify if the change i made to .net8 on Cloud was made.

Thank you it's a good start where to look.

**Comment by leekelleher** [comment]
@slag-dev I've patched up the Deploy Connector code (e.g. the `ToArtifact` bits), so fingers crossed this may resolve the issue on Umbraco Cloud. This patch is part of [Contentment v4.6.1](https://github.com/leekelleher/umbraco-contentment/releases/tag/4.6.1).
